name: Build and push to artifacts
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Setup Node.js environment
              uses: actions/setup-node@v6
              with:
                node-version: v24.x
            - name: install yarn
              run: npm i -g yarn
            - name: run yarn
              run: yarn
            - name: build release
              run: yarn prod
            - name: upload artifact
              uses: actions/upload-artifact@v7
              with:
                name: tmp-build
                path: dist/animated_java.js
                archive: false